=== metabolomics-us/mona/moa-server/schemas/UploadSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {

    "tag": {
      "title": "Tag Schema",
      "type": "object",
      "properties": {
        "text": {"type": "string"},
        "ruleBased": {"type": "boolean"}
      },
      "required": ["text"],
      "additionalProperties": false
    },
    "comment": {
      "type": "object",
      "properties": {
        "comment": {"type": "string"}
      },
      "required": ["comment"],
      "additionalProperties": false
    },
    "metaDataItem": {
      "title": "MetaData Item Schema",
      "type": "object",
      "properties": {
        "category": {"type": "string"},
        "computed": {"type": "boolean"},
        "name": {"type": "string"},
        "suspect": {"type": "boolean"},
        "reasonForSuspicion": {"type": "string"},
        "type": {"type": "string"},
        "unit": {
          "anyOf": [
            {},
            {"type": "null"},
            {"type": "string"}
          ]
        },
        "value": {"type": "string"}
      }
    },

    "compound": {
      "title": "Compound Schema",
      "type": "object",
      "properties": {
        "inchi": {
          "type": "string",
          "pattern": "^InChI=.*$"
        },
        "inchiKey": {
          "type": "string",
          "pattern": "[A-Z]{14}-[A-Z]{10}-[A-Z]"
        },
        "molFile": {"type": "string"},
        "metaData": {
          "type": "array",
          "items": [
            {"$ref": "#/definitions/metaDataItem"}
          ]
        },
        "names": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {"type": "string"}
              },
              "additionalProperties": false
            }
          ]
        },
        "comments": {
          "type": "array",
          "items": [
            {"$ref": "#/definitions/comment"}
          ]
        },
        "tags": {
          "type": "array",
          "items": [
            {"$ref": "#/definitions/tag"}
          ]
        },
        "dateCreated": {"type": "string"},
        "lastUpdated": {"type": "string"},
        "id": {"type": "integer"}
      },
      "anyOf": [
        {"required": ["molFile"]},
        {"required": ["inchi"]}
      ],
      "additionalProperties": false
    },

    "submitter": {
      "type": "object",
      "properties": {
        "firstName": {"type": "string"},
        "lastName": {"type": "string"},
        "emailAddress": {"type": "string"},
        "institution": {"type": "string"},
        "dateCreated": {"type": "string"},
        "lastUpdated": {"type": "string"},
        "id": {"type": "integer"}
      },
      "required": [
        "firstName",
        "lastName",
        "emailAddress"
      ]
    }
  },
  "title": "Spectrum Upload Schema",
  "type": "object",
  "properties": {
    "spectrum": {
      "type": "string",
      "pattern": "^(?:\\d+?(?:\\.\\d+?)?):(?:\\d+?(?:\\.\\d+?)?)(?: (?:\\d+?(?:\\.\\d+?)?):(?:\\d+?(?:\\.\\d+?)?))*?$"
    },
    "biologicalCompound": {"$ref": "#/definitions/compound"},
    "chemicalCompound": {"$ref": "#/definitions/compound"},
    "predictedCompound": {
      "anyOf": [
        {},
        {"type": "null"},
        {"$ref": "#/definitions/compound"}
      ]
    },
    "metaData": {
      "type": "array",
      "items": [
        {"$ref": "#/definitions/metaDataItem"}
      ]
    },
    "submitter": {"$ref": "#/definitions/submitter"},
    "comments": {
      "type": "array",
      "items": [
        {"$ref": "#/definitions/comment"}
      ]
    },
    "tags": {
      "type": "array",
      "items": [
        {"$ref": "#/definitions/tag"}
      ]
    },
    "dateCreated": {"type": "string"},
    "lastUpdated": {"type": "string"},
    "id": {"type": "integer"}
  },
  "required": [
    "spectrum",
    "biologicalCompound",
    "chemicalCompound",
    "submitter"
  ],
  "additionalProperties": false
}

=== metabolomics-us/mona/test-data/testset/simpleNoNameNoMeta.json
{
  "biologicalCompound": {
    "comments": 
    [
    ],
    "dateCreated": "2014-11-21T17:25:10Z",
    "id": 14171,
    "inchi": "InChI=1S/C14H10O5/c1-17-9-4-3-7-10(14(9)18-2)11(15)8-5-6-19-13(8)12(7)16/h3-6H,1-2H3",
    "inchiKey": "VMGYORRTCREVTB-UHFFFAOYSA-N",
    "lastUpdated": "2014-11-21T17:25:10Z",
    "metaData": 
    [
    ],
    "molFile": "OpenBabel11211417242D\n\n 19 21  0  0  0  0  0  0  0  0999 V2000\n   -5.2812    2.8090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.6831    3.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.5491   -0.1910    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -4.4152    0.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0000    1.6180    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.5878    0.8090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.6831    0.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.9511    1.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -4.4152    1.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.6831    1.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.8171    1.8090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.8171   -0.1910    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.9511    0.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.5491    1.8090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.8171    2.8090    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.8171   -1.1910    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -5.2812    1.8090    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.5491    2.8090    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.0000   -0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n  1 17  1  0  0  0  0\n  2 18  1  0  0  0  0\n  3  4  2  0  0  0  0\n  3  7  1  0  0  0  0\n  4  9  1  0  0  0  0\n  5  6  2  0  0  0  0\n  5  8  1  0  0  0  0\n  6 19  1  0  0  0  0\n  7 10  2  0  0  0  0\n  7 12  1  0  0  0  0\n  8 11  1  0  0  0  0\n  8 13  2  0  0  0  0\n  9 14  2  0  0  0  0\n  9 17  1  0  0  0  0\n 10 11  1  0  0  0  0\n 10 14  1  0  0  0  0\n 11 15  2  0  0  0  0\n 12 13  1  0  0  0  0\n 12 16  2  0  0  0  0\n 13 19  1  0  0  0  0\n 14 18  1  0  0  0  0\nM  END",
    "names": 
    [
    ],
    "tags": 
    [
    ]
  },
  "chemicalCompound": {
    "comments": 
    [
    ],
    "dateCreated": "2014-11-21T17:25:10Z",
    "id": 14171,
    "inchi": "InChI=1S/C14H10O5/c1-17-9-4-3-7-10(14(9)18-2)11(15)8-5-6-19-13(8)12(7)16/h3-6H,1-2H3",
    "inchiKey": "VMGYORRTCREVTB-UHFFFAOYSA-N",
    "lastUpdated": "2014-11-21T17:25:10Z",
    "metaData": 
    [
    ],
    "molFile": "OpenBabel11211417242D\n\n 19 21  0  0  0  0  0  0  0  0999 V2000\n   -5.2812    2.8090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.6831    3.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.5491   -0.1910    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -4.4152    0.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.0000    1.6180    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.5878    0.8090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.6831    0.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.9511    1.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -4.4152    1.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -2.6831    1.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.8171    1.8090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.8171   -0.1910    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.9511    0.3090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.5491    1.8090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.8171    2.8090    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -1.8171   -1.1910    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -5.2812    1.8090    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -3.5491    2.8090    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.0000   -0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n  1 17  1  0  0  0  0\n  2 18  1  0  0  0  0\n  3  4  2  0  0  0  0\n  3  7  1  0  0  0  0\n  4  9  1  0  0  0  0\n  5  6  2  0  0  0  0\n  5  8  1  0  0  0  0\n  6 19  1  0  0  0  0\n  7 10  2  0  0  0  0\n  7 12  1  0  0  0  0\n  8 11  1  0  0  0  0\n  8 13  2  0  0  0  0\n  9 14  2  0  0  0  0\n  9 17  1  0  0  0  0\n 10 11  1  0  0  0  0\n 10 14  1  0  0  0  0\n 11 15  2  0  0  0  0\n 12 13  1  0  0  0  0\n 12 16  2  0  0  0  0\n 13 19  1  0  0  0  0\n 14 18  1  0  0  0  0\nM  END",
    "names": 
    [
    ],
    "tags": 
    [
    ]
  },
  "comments": 
  [
  ],
  "dateCreated": "2014-11-21T19:56:03Z",
  "id": 69856,
  "lastUpdated": "2014-11-21T19:56:03Z",
  "metaData": 
  [
  ],
  "predictedCompound": null,
  "spectrum": "88.029500:307.000000 92.025600:323.000000 95.012600:592.000000 102.046600:1626.000000 103.054000:1187.000000 104.060900:263.000000 105.034500:673.000000 113.038900:3345.000000 114.046700:12195.000000 115.052500:1794.000000 116.058900:249.000000 117.033700:316.000000 119.013100:659.000000 120.020300:304.000000 121.028700:2851.000000 122.035400:501.000000 128.062300:304.000000 129.033800:732.000000 130.041500:2245.000000 131.049400:7328.000000 132.056600:2728.000000 133.060400:294.000000 135.044400:787.000000 137.059800:225.000000 140.025800:457.000000 141.033600:5468.000000 142.041400:14763.000000 143.045700:1478.000000 144.055200:206.000000 145.028700:2957.000000 146.032900:249.000000 149.023400:293.000000 155.060600:303.000000 157.028600:1651.000000 158.036400:5604.000000 159.043900:6141.000000 160.050300:1154.000000 165.055000:615.000000 168.020700:847.000000 169.028400:5922.000000 170.036100:9693.000000 171.042600:2329.000000 172.046200:278.000000 173.023300:2705.000000 174.027200:359.000000 185.023700:281.000000 186.031100:4214.000000 187.038600:6444.000000 188.043000:731.000000 197.023700:7185.000000 198.030700:4857.000000 199.036700:881.000000 201.018200:2795.000000 202.022100:349.000000 213.018200:733.000000 214.025500:1256.000000 215.033800:11949.000000 216.037800:1447.000000 217.040000:207.000000 225.022500:298.000000 226.026000:708.000000 227.033500:683.000000 241.013000:941.000000 242.017100:169.000000 243.028700:488.000000 259.024000:180.000000",
  "submitter": {
    "emailAddress": "wohlgemuth@ucdavis.edu",
    "firstName": "Gert",
    "id": 1,
    "lastName": "Wohlgemuth"
  },
  "tags": 
  [
  ]
}
